on:
  push:
    branch: [main]

defaults:
  run:
    working-directory: real-package

jobs:
  build:
    defaults:
      run:
        working-directory: real-package
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
      run: npm ci
      working-directory: real-package
      run: npm test
      working-directory: real-package
